account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('register/', UserRegister.as_view(), name='register'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:pk>', AddView.as_view(), name='add'),
    path('remove/<int:pk>', RemoveView.as_view(), name='remove'),
]

favorite/urls.py
from django.urls import path
from .views import *

app_name = 'favorite'

urlpatterns = [
    path('', FavoriteView.as_view(), name='favorites'),
    path('add/<int:pk>', AddView.as_view(), name='add'),
    path('remove/<int:pk>', RemoveView.as_view(), name='remove'),
]

product/urls.py
from django.urls import path
from .views import *

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='products'),
]

root/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('favorite/', include('favorite.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.contrib.auth.models import User
from django.db import models

from cart.manager import CartManager
from product.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart_items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.SmallIntegerField(default=1)
    modify = models.DateTimeField(auto_now=True)
    create_date = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    class Meta:
        ordering = ('-create_date',)

    def total_price(self):
        return self.quantity * self.product.price

favorite/models.py
from django.contrib.auth.models import User
from django.db import models

from product.models import Product


class Favorite(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='favorites')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='favorites')
    add_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-add_date',)

product/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images')
    is_available = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

    class Meta:
        ordering = ('name',)

account/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import RedirectView, FormView

from account.form import UserRegisterForm, UserLoginForm


class UserRegister(FormView):
    template_name = 'account/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('account:login')

    def form_valid(self, form):
        form.save(form.cleaned_data)
        messages.success(self.request, 'register was done successfully', 'success')
        return super().form_valid(self)


class UserLogin(FormView):
    template_name = 'account/login.html'
    form_class = UserLoginForm
    success_url = reverse_lazy('product:products')

    def form_valid(self, form):
        try:
            user = form.find_user(form.cleaned_data)
            login(self.request, user)
        except ValueError as ve:
            messages.error(self.request, str(ve), 'danger')
            return redirect(self.request.get_full_path())
        return super().form_valid(self)


class UserLogoutView(LoginRequiredMixin, RedirectView):
    pattern_name = 'account:login'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)

cart/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from cart.models import Cart
from product.models import Product


class CartView(LoginRequiredMixin, View):
    def get(self, request):
        cart_items = Cart.objects.filter(user=request.user)
        return render(request, 'cart/cart.html',
                      {'cart_items': cart_items, 'total_price': Cart.objects.total_price(request.user)})


class AddView(LoginRequiredMixin, View):
    def post(self, request, pk):
        product = Product.objects.filter(id=pk).first()
        if product:
            if product.is_available:
                Cart.objects.add(request.user, product)
                messages.success(request, 'product added successfully', 'success')
                return redirect('product:products')
            messages.warning(request, 'product is not available', 'danger')
            return redirect('product:products')
        messages.error(request, 'no product founded', 'danger')
        return redirect('product:products')


class RemoveView(LoginRequiredMixin, View):
    def post(self, request, pk):
        cart = Cart.objects.filter(product_id=pk, user=request.user).first()
        if cart:
            cart.delete()
            messages.success(request, 'product successfully removed', 'success')
            return redirect('cart:cart')
        messages.error(request, 'this product is not in your cart', 'danger')
        return redirect('cart:cart')

favorite/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from favorite.models import Favorite


class FavoriteView(LoginRequiredMixin, View):
    def get(self, request):
        favorites = Favorite.objects.filter(user=request.user)
        context = {'favorites': favorites}
        return render(request, 'favorite/favorites.html', context=context)


class AddView(LoginRequiredMixin, View):
    def post(self, request, pk):
        is_exist = not Favorite.objects.get_or_create(user=request.user, product_id=pk)[1]
        if is_exist:
            messages.warning(request, 'this product already exist in your favorites ', 'warning')
            return redirect('product:products')
        messages.success(request, 'product added to your favorites', 'success')
        return redirect('product:products')


class RemoveView(LoginRequiredMixin, View):
    def post(self, request, pk):
        favorite_filter = Favorite.objects.filter(user=request.user, product_id=pk)
        if favorite_filter.exists():
            favorite_filter.delete()
            messages.success(request, 'product removed from your favorites', 'success')
            return redirect('favorite:favorites')
        messages.error(request, 'product not exist', 'danger')
        return redirect('favorite:favorites')

product/views.py
from django.db.models import Count, F
from django.views.generic import ListView

from favorite.models import Favorite
from product.filters import ProductFilter
from product.form import FilterForm
from product.models import Product


class ProductListView(ListView):
    template_name = 'product/products.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q_param = self.request.GET
        form_initial = {
            'name': q_param.get('name', ''), 'category': q_param.get('category', '')
            , 'order': q_param.get('order', ''), 'available': q_param.get('available', None)
        }
        filter_form = FilterForm(initial=form_initial)
        context['filter_form'] = filter_form
        return context

    def get_queryset(self):
        return ProductFilter(self.request.GET, queryset=Product.objects.all()).qs

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% block title %}
    Cart
{% endblock %}

{% block content %}
    {% include 'inc/messages.html' %}
    <div class="offset-3 col-6">
        {% if not cart_items|length %}
            <br>
            <h3 class="text-center"> there is no product in your cart </h3>
            <br>
        {% endif %}
        <br><br>
        <h5>total price: {{ total_price }}</h5>
        {% for cart_item in cart_items %}
            <div class="card my-3 p-2">
                <p class="card-title h5">Product Name: {{ cart_item.product.name }}</p>
                <p class="card-title h6">quantity: {{ cart_item.quantity }}</p>
                <p class="card-title h6">Total Price {{ cart_item.total_price }}</p>
                <form action="{% url 'cart:remove' cart_item.product.pk %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger " value="Remove" type="submit">
                </form>
            </div>
        {% endfor %}
    </div>

{% endblock %}

favorite/templates/favorite/favorites.html
{% extends 'base.html' %}>
{% block title %}
    Favorites
{% endblock %}

{% block content %}
    {% include 'inc/messages.html' %}
    <div class="offset-3 col-6">
        {% if not favorites|length %}
            <br>
            <h3 class="text-center"> there is no product in your favorites </h3>
            <br>
        {% endif %}
        {% for favorite in favorites %}
            <div class="card my-3 p-2">
                <p class="card-title h5">Product Name: {{ favorite.product.name }}</p>
                <form action="{% url 'favorite:remove' favorite.product.pk %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger " value="Remove" type="submit">
                </form>
            </div>
        {% endfor %}
    </div>
{% endblock %}

product/templates/product/products.html
{% extends 'base.html' %}
{% block title %}
    Products
{% endblock %}

{% block content %}
    <br>
    {% include 'inc/messages.html' %}
    <div class="row">
        <div class="offset-4 col-4">
            <form class="row" name="filter_form" action="" method="get">
                {% csrf_token %}
                {{ filter_form.as_p }}
                <input type="submit" value="Do Filter" class="btn btn-info col-3 mx-2">
            </form>
        </div>

    </div>
    <br><br>
    <div class="offset-1 row">
        {% for product in products %}
            <div class="col-lg-2 col-md-3 col-sm-6 mx-2 my-4 ">
                <div class="card border border-2 border-secondary px-1">
                    <img src="{{ product.image.url }}" class="card-img " style="height: 200px" alt="">
                    <p class="card-title mx-1 mt-1 " style="font-family: SansSerif,cursive">{{ product.name }}</p>
                    <div class="row">
                        <p class="card-title pe-0 col-4 ">{{ product.price }} $</p>
                        {% if not product.is_available %}
                            <small class="text-danger card-title col-7"> not available</small>
                        {% endif %}
                    </div>
                    <form action="{% url 'cart:add' product.pk %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-success mx-2 mt-3 pe-3 text-center col-11" value="Add To Cart"
                               type="submit">
                    </form>
                    <form action="{% url 'favorite:add' product.pk %}" method="post">
                        {% csrf_token %}
                        <input class="btn btn-danger mx-2 my-1 col-11" value="Add To Favorite" type="submit">
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body id="body">
{% include 'inc/navbar.html' %}

{% block content %}

{% endblock %}
<br><br>
{% include 'inc/footer.html' %}
</body>
</html>

templates/inc/footer.html
<section class="">
  <footer class="text-center text-white" style="background-color: #2a3036;">
    <div class="container p-4 pb-0">
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Author: moheb moallem</span>
        </p>
      </section>
    </div>
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      Email:
      <a class="text-white" href="mailto:mohebmoallem1376@gmail.com">mohebmoallem1376@gmail.com</a>
    </div>
  </footer>
</section>

templates/inc/messages.html
{% if messages %}
    <br>
    <ul class="messages offset-3 col-6">
        {% for message in messages %}
            <li{% if message.tags %} class="h5 alert alert-{{ message.tags }} text-center"{% endif %}
                                     style="list-style-type: none">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark justify-content-end " style="background-color: #363a42">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link mx-4 " href="{% url 'product:products' %}">Home</a>
            {% if request.user.is_authenticated %}
                <a class="nav-item nav-link mx-4 " href="{% url 'account:logout' %}">Logout</a>
                <a class="nav-item nav-link mx-4 " href="{% url 'cart:cart' %}">Cart</a>
                <a class="nav-item nav-link mx-4 " href="{% url 'favorite:favorites' %}">Favorites</a>
            {% else %}
                <a class="nav-item nav-link  mx-4" href="{% url 'account:register' %}">Register </a>
                <a class="nav-item nav-link mx-4 " href="{% url 'account:login' %}">Login</a>
            {% endif %}
        </div>
    </div>
</nav>